#!/usr/bin/env python3
"""Public facade module for Teledyne LeCroy oscilloscope control."""

from teledyne_lecroy_core import (
    SETTINGS_OPTIONS,
    AcquisitionConfig,
    AuxOutputMode,
    ChannelConfig,
    ChannelTrigger,
    Coupling,
    ScopeConfigurationError,
    ScopeConnectionError,
    ScopeError,
    ScopeTimeoutError,
    ScopeTriggerError,
    SequenceConfig,
    SequenceData,
    TeledyneLecroyScope,
    TriggerConfig,
    TriggerSlope,
    TriggerState,
    WP804HD,
    WR8208HD,
    WaveformData,
)

__all__ = [
    "TriggerSlope",
    "TriggerState",
    "Coupling",
    "AuxOutputMode",
    "SETTINGS_OPTIONS",
    "ScopeError",
    "ScopeConnectionError",
    "ScopeTimeoutError",
    "ScopeConfigurationError",
    "ScopeTriggerError",
    "ChannelConfig",
    "ChannelTrigger",
    "TriggerConfig",
    "AcquisitionConfig",
    "SequenceConfig",
    "WaveformData",
    "SequenceData",
    "TeledyneLecroyScope",
    "WP804HD",
    "WR8208HD",
]
